### PR TITLE
Updated SDFiles, Kernelpatcher

### PR DESCRIPTION
**Pull request by tumGER**
+ Fixed possible bug with hekate_ipl
+ Updated to newest SDFiles (See SDFilesSwitch Changelog)
+ Fixed typo in Form1
+ Updated to newest kernelpatcher (as @thomasnet-mc requested in #4 )

### CODE REVIEW

**Comment by tumGER** [comment]
Important - I just looked into the way to copy files to the SD. You have to change some of it in order to make it work with this commit!

**Comment by imPRAGMA** [comment]
Can you explain about the SD thing? What do I have to change?

**Comment by imPRAGMA** [comment]
Also this cant be right? Whats up with the large spaces
https://i.imgur.com/1PJfTxs.png

**Comment by tumGER** [comment]
Its centered, see the newest SDFiles for a demo

The files that are copied have to be changed to fit the new file structure of the SDFiles

**Comment by tumGER** [comment]
Isn't needed anymore, SDFiles V3 already does what this program does (LayeredFS) ^^'

**Pull request closed without merging**
